# Generated by Django 3.0.4 on 2020-04-14 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200415_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 22, 54, 13, 734052, tzinfo=utc)),
        ),
    ]
